en/administration/security/authorization.md
Documentation for rundeck/rundeck#3456
=> Documentation on job by uuid for acl

en/manpages/man1/rd-acl.md
Documentation on `rd-acl` tool for rundeck/rundeck#3470
=> Documentation rd-acl tool

en/administration/configuration/gui-customization.md
Update docs for custom logo installation.
=> Add docs for job pagination settings.

en/administration/security/authentication.md
New encryption utility will be used to encrypt passwords for the realm.properties file.
=> Add information for using new password encryption utility 

en/administration/configuration/config-file-reference.md, en/administration/configuration/project-setup.md
re: https://github.com/rundeck/rundeck/pull/3678
=> Add project nodes synch load docs

en/administration/configuration/encryptable-properties.md
Docs showing how to use builtin password encryptor in Rundeck for use with Pro property decryption feature.
=> Update the password generation documentation for the Pro property encryption

en/edam.conf, en/templates/navCrumbs.template, scripts/edam.groovy
Adds "edit this page" and "Report an issue" links to each generated page, with links back to github to edit the page or create a documentation issue.
=> Add edit-source link and issue report links in nav/page templates

scripts/ci-deploy.sh
docs in case there were removed or renamed files
=> Update deploy script, remove any pre-existing files from generated

en/templates/html.template, scripts/ci-common.sh
instead of 3.0.x-SNAPSHOT dir
* also update jquery js link to use https
=> Deploy 3.0.x to 3.0.x/ dir

en/administration/security/sso.md
Without this property set correctly SSO won't work.
=> Add the property that enables the SSO feature to the docs.

en/administration/security/ssl.md
ref https://github.com/rundeck/rundeck/pull/3848
=> Update docs for forwarded headers using jetty

en/manual/job-plugins.md, en/manual/node-steps/jira-node-step-plugins.md, en/manual/notifications/jira-notification-plugins.md, en/manual/workflow-steps/jira-workflow-step-plugins.md
Documentation for Jira Pro only plugins
=> Jira plugins

en/plugins/index.md, en/toc.conf
Now we can have a single view of all the plugins and their availability. Not sure if it would be feasible to make the table sortable/filterable, but now at least people can ctrl-f on this page to find stuff.
=> add plugin index page

en/administration/configuration/email-settings.md
notification plugin development page
=> Fix incorrect links: mail plugin config, and

en/administration/install/tomcat.md
fresh rd3 install on linux and windows
=> rd3+tomcat

en/administration/install/tomcat.md
Reverts rundeck/docs#107
(merged prematurely)
=> Revert "rd3+tomcat"

en/tutorials/custom-script-plugin-db-cred-rotation.md, en/tutorials/custom-script-plugin-hello-world.md, en/tutorials/toc.conf
Associated code is here https://github.com/clofresh/rundeck-playground
=> Add custom script plugin tutorials

en/edam.conf, scripts/edam.groovy
Updates the link for page bug reports to include source file path, and references the github issue template
=> Bug report link enhancement

en/upgrading/upgrading-to-rundeck3.md
=> add tomcat upgrade

en/administration/security/authentication.md
Fixes #12  and #121.
Also formatting of file paths.
=> Updated and corrected configuration values

en/administration/configuration/database/secure_mssql.md, en/administration/configuration/database/toc.conf
How to enable security mode in MS SQL Server
=> Security mode with SQL Server

en/administration/configuration/plugins/bundled-plugins.md
=> Fix broken links in bundled-plugins.md

en/administration/configuration/database/index.md, en/administration/configuration/database/postgres.md, en/administration/install/tomcat.md
=> various db edition

en/administration/security/authentication.md
Docs for feature https://github.com/rundeck/rundeck/pull/4202
=> Docs for command line Jaas authorization testing tool.

en/administration/security/authorization.md
Documentation for rundeck/rundeck#4220
`scm_create`, `scm_delete`, `scm_update` new permissions.
=> scm_* acl special permission

en/administration/configuration/plugins/configuring.md
Include information about `removePathPrefix` for storage plugins, and add more information about multiple storage and converter plugins.
=> Updates to storage configuration docs

en/developer/01-plugin-development.md
Add anchor link to groovy plugin development from first paragraph
=> Fix: missing link for notification plugins

en/administration/configuration/config-file-reference.md
=> Session timeout settings for RD 3 in Tomcat

en/administration/configuration/config-file-reference.md, en/administration/security/toc.conf, en/administration/security/webapp-http-headers.md
ref https://github.com/rundeck/rundeck/pull/4405
=> Add docs for security http-headers

en/developer/12-option-values-plugins.md
Forgot to add the instructions for enabling this plugin.
=> Add docs for enabling option values plugin.

en/developer/01-plugin-development.md, en/developer/02-plugin-annotations.md
for https://github.com/rundeck/rundeck/pull/4393
=> Add docs for plugin provider metadata

en/administration/configuration/database/edam.conf, en/administration/configuration/database/index.md, en/administration/configuration/database/mysql.md
* Add MySQL 5.6 utf8mb4 instructions
* Recommend MySQL 5.7
* Bring database page links to top of index page
=> Add MySQL 5.6 utf8mb4 instructions

en/developer/13-user-group-source-plugin.md, en/developer/toc.conf
Documentation for User Group Source plugins.
=> Documentation for User Group Source plugins.

en/administration/configuration/config-file-reference.md
Document local login form enable/disable property.
=> Document local login form enable/disable property.

en/administration/configuration/config-file-reference.md
Documentation for logout behavior properties.
=> Documentation for logout behavior properties.

en/api/rundeck-api.md
This PR updates the query metrics api documentation according to changes from https://github.com/rundeck/rundeck/pull/4667
=> update metrics api documentation

en/administration/security/sso.md
Docs for Okta user group plugin.
=> Docs for Okta user group plugin.

.gitignore, en/administration/security/sso.md
=> Ping SSO documentation

en/manpages/man5/aclpolicy-v10.md
Documentation for rundeck/rundeck#4769
`notBy` clause for ACL
=> documentation for notBy acl clause

en/manual/creating-jobs.md
https://www.freeformatter.com/cron-expression-generator-quartz.html site to create and test crontabs added.
=> Web tool to generate and test crontabs added

en/api/rundeck-api.md
Documentation for rundeck/rundeck#4986
=> doc for forecast past argument

en/administration/security/authentication.md
Informs users of PropertyFileLoginModule of the behavior of that module.
=> Add note regarding security implications of PropertyFileLoginModule

en/manual/01-introduction.md
=> Correct typo, update url Fix #272

en/api/rundeck-api.md
Documentation for rundeck/rundeck#4955 and rundeck/rundeck#5069
=> Add multiple jobs ids to scheduler/takeover endpoint

en/manual/node-steps/sqlrunner.md
Documentation for enhancement to sqlrunner to accept inline script and variables.
rundeckpro/rundeckpro#646
=> SQLRunner script inline enhancement 

en/upgrading/toc.conf, en/upgrading/upgrading-to-rundeck-3.1.md
WIP:
Please comment with Rundeck 3.1 upgrade guide information: Breakages, configuration changes, install requirements, etc.
=> Upgrading guide for Rundeck 3.1

docs/manual/job-workflows.md
changes moved for vuepress
(orig https://github.com/rundeck/docs/pull/293)
=> Fix typos 

docs/administration/cluster/loadbalancer/haproxy.md
move changes to vuepress branch
(orig https://github.com/rundeck/docs/pull/281)
=> Fix haproxy content

docs/api/rundeck-api.md
=> Add job workflow endpoint to API docs

docs/.vuepress/sidebar-menus/plugin-development.js, docs/developer/audit-events-listeners.md
Documentation for Audit Listener Plugins, described at: https://github.com/rundeck/rundeck/pull/5028
=> Documentation for Audit Listener Plugins

docs/developer/execution-lifecycle.md, docs/developer/job-lifecycle.md
* content update
* add example code links
=> Lifecycle plugin dev guide updates

docs/developer/execution-lifecycle.md, docs/manual/execution-lifecycle/job-resume.md
* Adds instructions for enabling job resume in docker
* Consistent instruction formatting
=> Docker Job Resume

docs/developer/execution-lifecycle.md, docs/manual/execution-lifecycle/job-resume.md
…n and job resume (now enabled by default)
=> Update: job resume/execution lifecycle enabled by default

docs/administration/install/windows.md
minor grammar corrections. more soon.
=> updated windows.md

docs/manual/execution-lifecycle/job-resume.md
* Addresses application crash
* Addresses behavior with job ref steps
=> Add job resume limitations section

docs/administration/security/sso.md
Add new docs for using a custom redirect url with SSO.
=> Add new docs for using a custom redirect url with SSO.

docs/manual/notifications/email.md
Fixed broken link.  I would like you to review how to make anchor text and links.
=> Fix broken links in notifications/email.md

docs/developer/01-plugin-development.md
for PR https://github.com/rundeck/rundeck/pull/5530
=> Private data context docs on Node Executor Script Plugin

docs/.vuepress/config.js, docs/developer/content-converter-plugins.md, docs/manual/content-converters/index.md, package-lock.json, package.json
There were numerous SEO issues currently
I added two plugins that will help:
- Auto-meta will automatically generate meta descriptions and Open graph meta
- Canonical will alleviate situations when a page has an index.html and add a proper canonical referencing the / version of the page
=> add auto meta tag information and canonical links to page

docs/developer/06-logging-plugins.md, docs/enterprise/index.md
- adding docs for deleteFile in Execution Log Files plugins
- adding extra setting on s3 PRO plugin to delete remote files
=> Execution Log Files plugin delete files docs

docs/administration/configuration/config-file-reference.md, docs/administration/install/docker.md, docs/administration/install/tomcat.md, docs/upgrading/upgrading-to-rundeck3.md
mostly format changes, and removing obsolete stuff
=> mostly format changes

docs/administration/configuration/config-file-reference.md
Add docs for requiredRole configuration property.
=> Add docs for requiredRole configuration property.
